buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
    }
}

apply plugin: 'com.android.application'

def signingFile = file 'signing.gradle'
if (signingFile.exists()) apply from: signingFile
def signingBetaFile = file 'signing-beta.gradle'
if (signingBetaFile.exists()) apply from: signingBetaFile

allprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:all" << "-Xlint:-deprecation" << "-Xlint:-dep-ann"
    }
}

android {
    namespace = 'se.lublin.mumla'
    compileSdk = 35
    ndkVersion = '25.1.8937393'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    base { archivesName = "mumla" }
    buildFeatures { buildConfig = true }

    def gitDescribe = providers.exec {
        commandLine "git", "describe", "--tags", "--match", "[0-9]*.[0-9]*.[0-9]*", "--always"
    }.standardOutput.asText.get().trim()

    defaultConfig {
        minSdk = 21
        targetSdk = 34
        applicationId "se.lublin.mumla"
        versionCode 3070301
        versionName gitDescribe
        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
        buildConfigField "String", "VERSIONTAG", "\"" + gitDescribe.split("-")[0] + "\""
        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    flavorDimensions "release"
    productFlavors {
            beta {
    dimension "release"
    applicationId "se.lublin.humla"
}

    }

    buildTypes {
        release {
            if (android.hasProperty("signingConfigs")) {
                if (signingConfigs.hasProperty("release")) signingConfig = signingConfigs.release
                if (signingConfigs.hasProperty("beta")) signingConfig = signingConfigs.beta
            }
        }
        debug {
            versionNameSuffix "-debug"
            if (android.hasProperty("signingConfigs")) {
                if (signingConfigs.hasProperty("beta")) signingConfig = signingConfigs.beta
            }
        }
    }

    lint {
        abortOnError = true
        disable 'InvalidPackage', 'MissingTranslation'
        explainIssues = true
        ignoreWarnings = false
        quiet = false
    }

    applicationVariants.all { variant ->
        if (variant.flavorName == "beta") {
            variant.outputs.each { output ->
                output.versionCodeOverride = System.currentTimeSeconds() / 60
            }
        }
    }
}

dependencies {
    implementation 'com.google.protobuf:protobuf-java:3.11.4'
    implementation 'com.madgag.spongycastle:core:1.51.0.0'
    implementation 'com.madgag.spongycastle:prov:1.51.0.0'
    implementation 'com.madgag.spongycastle:pkix:1.51.0.0'
    implementation 'com.googlecode.javacpp:javacpp:0.7'
    implementation 'org.jetbrains:annotations:18.0.0'
    implementation 'org.minidns:minidns-hla:0.3.4'
    implementation 'org.minidns:minidns-android21:0.3.4'
    implementation 'com.google.guava:guava:28.2-android'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.documentfile:documentfile:1.1.0'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.2'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'org.jsoup:jsoup:1.13.1'
    implementation 'info.guardianproject.netcipher:netcipher:2.1.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20251224'
}
